# Generated by Django 4.0 on 2022-01-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caricature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caricature_Img', models.ImageField(blank=True, null=True, upload_to='caricature/')),
                ('Caricature_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Graphic_Img', models.ImageField(blank=True, null=True, upload_to='graphic/')),
                ('Graphic_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Illustration_Img', models.ImageField(blank=True, null=True, upload_to='illustration/')),
                ('Illustration_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portrait_Img', models.ImageField(blank=True, null=True, upload_to='portrait/')),
                ('Portrait_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
