# Generated by Django 4.0 on 2022-01-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artadmin', '0002_caricature_graphic_illustration_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Name', models.CharField(default='', max_length=20)),
                ('Contact_Email', models.EmailField(default='', max_length=254)),
                ('Contact_Message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
